### ISSUE TITLE
Features to integrate

### ISSUE THREAD

**Issue by animesh-007** [animesh-007/tcga-download#1]
- [ ] Add feature to download files in the classes folder directly.
- [ ] Multi-thread the for loop
- [ ] Add tqdm for multi-thread code accordingly

**Comment by gakash2k01** [comment]
#2


> * [x]  Add feature to download files in the classes folder directly.
> * [x]  Multi-thread the for loop
> * [x]  Add tqdm for multi-thread code accordingly
